
import java.util.Scanner;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author epidu
 */
public class carnetEstudiantil extends javax.swing.JFrame {
           DefaultListModel modelo = new DefaultListModel();
           ArbolBinarioBusqueda arbol = new ArbolBinarioBusqueda();
           Scanner sc = new Scanner(System.in);
           String valores ="";

           /**
            * Creates new form carnetEstudiantil
            */
           public carnetEstudiantil() {
                      initComponents();
                      this.setLocationRelativeTo(null);
                      jList1.setModel(modelo);
                      modelo.removeAllElements();
                      modelo.addElement("1. Agregar un carnet");
                      modelo.addElement("2. Ver los carnet en Orden");
                      modelo.addElement("3. Buscar un numero de carnet");
                      modelo.addElement("4. Mostrar la cantidad de carnets registrados");
                      modelo.addElement("5. El carnet mas reciente");
                      modelo.addElement("6. El carnet mas antiguo");
                      modelo.addElement("7. Eliminar un Carnet");
           }

           /**
            * This method is called from within the constructor to initialize
            * the form. WARNING: Do NOT modify this code. The content of this
            * method is always regenerated by the Form Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jScrollPane1 = new javax.swing.JScrollPane();
                      jList1 = new javax.swing.JList<>();
                      jLabel1 = new javax.swing.JLabel();
                      jButton1 = new javax.swing.JButton();
                      jScrollPane2 = new javax.swing.JScrollPane();
                      Resultado = new javax.swing.JTextArea();
                      jLabel2 = new javax.swing.JLabel();
                      jTextField1 = new javax.swing.JTextField();
                      jTextCarnet = new javax.swing.JFormattedTextField();
                      jLabel3 = new javax.swing.JLabel();

                      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                      jList1.setModel(new javax.swing.AbstractListModel<String>() {
                                 String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                                 public int getSize() { return strings.length; }
                                 public String getElementAt(int i) { return strings[i]; }
                      });
                      jScrollPane1.setViewportView(jList1);

                      jLabel1.setText("Control de Carnet de la Universidad");

                      jButton1.setText("Ejecutar Proceso");
                      jButton1.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jButton1ActionPerformed(evt);
                                 }
                      });

                      Resultado.setColumns(20);
                      Resultado.setRows(5);
                      jScrollPane2.setViewportView(Resultado);

                      jLabel2.setText("Numero de Carnet (20XX1XX0XXX):");

                      try {
                                 jTextCarnet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("20##1##0###")));
                      } catch (java.text.ParseException ex) {
                                 ex.printStackTrace();
                      }
                      jTextCarnet.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            jTextCarnetActionPerformed(evt);
                                 }
                      });

                      jLabel3.setText("Tiempo de ejecucion");

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                      getContentPane().setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(0, 0, Short.MAX_VALUE)
                                                                  .addComponent(jLabel1))
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addContainerGap()
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addComponent(jScrollPane1)
                                                                             .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                        .addComponent(jLabel2)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(jTextCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                                       .addComponent(jTextField1)
                                                       .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(12, 12, 12))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addComponent(jButton1)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addComponent(jLabel3)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jTextCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      );

                      pack();
           }// </editor-fold>//GEN-END:initComponents

           private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//                      Resultado.setText(jList1.getSelectedValue())
                        long Tinicio, Tfin, tiempo;
                      Tinicio = System.currentTimeMillis();
                      long valor;
                      arbol.setValor("");
                      if (jList1.getSelectedIndex() == 0){
//                                 Agregar un carnet
                                   valor = Long.parseLong(jTextCarnet.getText());
                                   Resultado.setText(arbol.insertarNodo(arbol.getRaiz1(), new Nodo(valor)));
                      }else if(jList1.getSelectedIndex() == 1){
//                                 Ver los carnet en Orden
                                   String valor1 = "";
                                    valor1 = arbol.recorrerEnOrden2(arbol.getRaiz1());
                                   Resultado.setText(valor1);
                      }else if(jList1.getSelectedIndex() == 2){
//                                 Buscar un numero de carnet
                                    valor = Long.parseLong(jTextCarnet.getText());
                                   Nodo encontrado = arbol.buscarNodo(arbol.getRaiz1(), valor);
                    
                    if(encontrado != null) {
                        
                        Resultado.setText("Se encontro el Carnet: " + encontrado.getData());
                        
                    }else {
                        
                        Resultado.setText("No se encontro dicho Carnet");
                        
                    }
                      }else if(jList1.getSelectedIndex() == 3){
                                 long cuenta = arbol.contarNodos(arbol.getRaiz1());
                    
                                 Resultado.setText("Hay " + cuenta + " carnets registrados");
                                 
                      }else if(jList1.getSelectedIndex() == 4){
                                 String valor1 = "";
                                    valor1 = arbol.recorrerEnOrden3(arbol.getRaiz1());
                                   Resultado.setText(valor1);
                                 
                                 
                      }else if(jList1.getSelectedIndex() == 5){
                                 String valor1 = "";
                                    valor1 = arbol.recorrerEnOrden2(arbol.getRaiz1());
                                   Resultado.setText(valor1.substring(0,11));
                                 
                      }else if(jList1.getSelectedIndex() == 6){
                                 
                      }
                      Tfin = System.currentTimeMillis();
                      tiempo = Tfin-Tinicio;
                      String s = String.valueOf(tiempo);
                      jTextField1.setText(s);
           }//GEN-LAST:event_jButton1ActionPerformed

           private void jTextCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCarnetActionPerformed
                      // TODO add your handling code here:
           }//GEN-LAST:event_jTextCarnetActionPerformed

           /**
            * @param args the command line arguments
            */
           public static void main(String args[]) {
                      /* Set the Nimbus look and feel */
                      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                       */
                      try {
                                 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                            if ("Nimbus".equals(info.getName())) {
                                                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                       break;
                                            }
                                 }
                      } catch (ClassNotFoundException ex) {
                                 java.util.logging.Logger.getLogger(carnetEstudiantil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (InstantiationException ex) {
                                 java.util.logging.Logger.getLogger(carnetEstudiantil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (IllegalAccessException ex) {
                                 java.util.logging.Logger.getLogger(carnetEstudiantil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                                 java.util.logging.Logger.getLogger(carnetEstudiantil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                      }
                      //</editor-fold>

                      /* Create and display the form */
                      java.awt.EventQueue.invokeLater(new Runnable() {
                                 public void run() {
                                            new carnetEstudiantil().setVisible(true);
                                 }
                      });
           }

           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JTextArea Resultado;
           private javax.swing.JButton jButton1;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JList<String> jList1;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JScrollPane jScrollPane2;
           private javax.swing.JFormattedTextField jTextCarnet;
           private javax.swing.JTextField jTextField1;
           // End of variables declaration//GEN-END:variables
}
